print("Welcome to Your Brand Name Generator v1.0\n")
city = (input("Which city did you grow up in?\n"))
pet = (input("What is the name of your pet?\n"))
brand_name = (city + " "+pet)
print(brand_name)
